### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by tpro** [SammyJames/ror_launch#1]
error[E0432]: unresolved import `tempfile::NamedTempFileOptions`
  --> src/main.rs:26:31
   |
26 | use tempfile::{NamedTempFile, NamedTempFileOptions};
   |                               ^^^^^^^^^^^^^^^^^^^^ no `NamedTempFileOptions` in the root

error[E0599]: no method named `write_fmt` found for type `&std::path::Path` in the current scope
   --> src/main.rs:116:9

**Comment by SammyJames** [comment]
is this related to your pr?

**Comment by tpro** [comment]
yep, outdated

**Comment by SammyJames** [comment]
cool ty
